In [6]:
import pandas as pd
import scipy
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Importing

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
scaler = MinMaxScaler()

In [ ]:
# another way. just different based on directory thing?
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()

# Data Pre-processing

In [28]:
# Load dataset
from sklearn.datasets import load_iris

data = load_iris()
data.keys()

# pd.DataFrame(data = data.data, columns = data.feature_names)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [27]:
for key in all_keys:
    print(data[key])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Duplicate values

In [ ]:
# Find

df.duplicated().sum()

In [ ]:
# Remove

df = df.drop_duplicates()

In [ ]:
1. Missing values 

In [ ]:
`df.isnull().sum()`

In [ ]:
- decide how to handle missing values

In [ ]:
- remove rows with missing values 
`df.dropna()`

In [ ]:
- imput missing values with mean, median, or mode 
`df.fillna(df.mean())`

In [1]:

        
2. Encode categorical variables
    - identify `df.select_dtypes(include=['object']).columns`
    - choose encoding method
        - one-hot
            `pd.get_dummies(df, columns=caegorical_cols)`
        - label
            ```from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])```
3. Feature scaling
    - import `from sklearn.preprocessing import StandardScaler`
    - choose scaling method
        - StandardScaler
            ```scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)```
        - MinMaxScaler
            ```from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)```

SyntaxError: invalid syntax (1553292181.py, line 1)

In [ ]:
from sklearn.model_selection import train_test_split
df = df.fillna(df.mean())
train, test = train_test_split(df)
train